version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/appdeploy/
file_exists_behavior: OVERWRITE 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root