version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/appdeploy/
permissions:
  - object: /home/ubuntu/appdeploy/
    owner: ubuntu
    group: ubuntu 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  
